print(0 is None)
print(0.0 is None)
print(0 is None)
print(None is 0)
print(None is 0.0)
print(None is 0)

print()
print(0 is not None)
print(0.0 is not None)
print(0 is not None)
print(None is not 0)
print(None is not 0.0)
print(None is not 0)
