print(0 == None)
print(0.0 == None)
print(0 == None)
print(None == 0)
print(None == 0.0)
print(None == 0)

print()
print(0 != None)
print(0.0 != None)
print(0 != None)
print(None != 0)
print(None != 0.0)
print(None != 0)
