import math
print("integers")
print(1 + True)
print(2 - True)
print(3 * False)
print(4 / True)
print(5 % True)
print(6 ** False)
print("floats")
print(1.5 + True)
print(2.5 - True)
print(3.5 * False)
print(4.5 / True)
print(5.5 % True)
print(6.5 ** False)
print("longs")
print(1 + True)
print(2 - True)
print(3 * False)
print(4 / True)
print(5 % True)
print(6 ** False)
print("math module")
print(math.fabs(True))
print(math.cos(True))
